### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by thecodeduchess** [lposavad/U4D16TeaCozy#2]
Readme pages have many functions. They generally function as documentation of a particular project. It can explain the usage or explain what the project is. In more involved projects, you may want to include a readme. If you want to write a really nice one, you will have to learn the "markdown" language.

 Here is some documentation on that:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
https://daringfireball.net/projects/markdown/syntax

**Comment by lposavad** [comment]
Thank you for the tip on the README file. Going forward in the course, I think I'll use it to capture the things I learn during a project. I'll also investigate the 'markdown' language (always another language to learn, isn't there?).
