### ISSUE TITLE
HTML/CSS

### ISSUE THREAD

**Issue by thecodeduchess** [lposavad/U4D16TeaCozy#3]
The code in these files are on point.

**Comment by lposavad** [comment]
Thanks! My process during this project was to setup HTML and CSS based on what I knew/remembered/could look up. This only got me so far! Once I got to a certain point, I did resort to analyzing the example page to learn how layouts and behaviors were implemented.
Going forward, I plan to analyze a lot of pages to understand how others implement layout, style and behavior. There's a wealth of information out there if you just press f12... :-)
